In [ ]:
import pandas as pd
import numpy as np

Inventories and conversion tools

In [ ]:
diphthongs = {"aw", "ay", "ey", "ow", "oy"}
timit_to_ipa = {
# vowels
    "aa": "ɑ",    # father
    "ae": "æ",    # trap
    "ah": "ʌ",    # strut
    "ao": "ɔ",    # thought
    "aw": "aʊ",   # mouth
    "ay": "aɪ",   # price
    "ax": "ə",    # comma (schwa)
    "ax-h": "ə",  # aspirated schwa (treat as schwa)
    "axr": "ə\u02de",   # nurse (r-colored schwa)
    "eh": "ɛ",    # dress
    "er": "ɜ˞",    # bird (r-colored vowel)
    "ey": "eɪ",   # face
    "ih": "ɪ",    # kit
    "ix": "ɨ",    # high central unrounded (near-schwa)
    "iy": "i",    # fleece
    "ow": "oʊ",   # goat
    "oy": "ɔɪ",   # choice
    "uh": "ʊ",    # foot
    "uw": "u",    # goose
    "ux": "ʉ",     # dude
# marginal sounds
    "ax-h": "ə̥",
    "bcl":  "b̚",
    "dcl":  "d̚",
    "eng":  "ŋ̍",
    "gcl":  "ɡ̚",
    "hv":   "ɦ",
    "kcl":  "k̚",
    "pcl":  "p̚",
    "tcl":  "t̚",
    "pau":  "|",
    "epi":  "||",
    "h#":   "#",
# consonants
    "b":   "b",    # B
    "ch":  "t͡ʃ",   # CH
    "d":   "d",    # D
    "dh":  "ð",    # DH
    "dx":  "ɾ",    # DX
    "el":  "l̩",   # EL
    "em":  "m̩",   # EM
    "en":  "n̩",   # EN
    "f":   "f",    # F
    "g":   "ɡ",    # G
    "hh":  "h",    # HH
    "h":   "h",
    "jh":  "d͡ʒ",   # JH
    "k":   "k",    # K
    "l":   "l",    # L
    "m":   "m",    # M
    "n":   "n",    # N
    "nx":  "ŋ",    # NX
    "ng":  "ŋ",    # NG
    # "nx": "ɾ̃",
    "p":   "p",    # P
    "q":   "ʔ",    # Q
    "r":   "ɹ",    # R
    "s":   "s",    # S
    "sh":  "ʃ",    # SH
    "t":   "t",    # T
    "th":  "θ",    # TH
    "v":   "v",    # V
    "w":   "w",    # W
    "wh":  "ʍ",    # WH
    "y":   "j",    # Y
    "z":   "z",    # Z
    "zh":  "ʒ",    # ZH
}

In [ ]:
# substitute the marginal sounds with close counterparts
allophones_substitute = {
    "ax-h": "ə",
    "bcl":  "b",
    "dcl":  "d",
    "eng":  "ŋ",
    "gcl":  "ɡ",
    "hv":   "h",
    "kcl":  "k",
    "pcl":  "p",
    "tcl":  "t",
    "el":  "l",
    "em":  "m",
    "en":  "n",
    # "axr": "ɹ",
    # "er":  "ɹ"
}

In [ ]:
# in timit annotation, we use this method for substituting diphthongs
split_diphthongs_TIMIT = {'oy': ['oh', 'y'],
 'ow': ['o', 'w'],
 'ay': ['a', 'y'],
 'aw': ['a', 'w'],
 'ey': ['e', 'y']}
split_diphtongs_IPA = {d: list(d) for d in ['aɪ', 'aʊ', 'eɪ', 'oʊ', 'ɔɪ']}

Yoruba and English sound correspondences

In [ ]:
# making those substitutions to get the English inventory
timit_to_ipa_sub = timit_to_ipa.copy()
for sound in allophones_substitute:
    timit_to_ipa_sub[sound] = allophones_substitute[sound]
english_ipa = set([v for k, v in timit_to_ipa_sub.items()])

In [ ]:
delete = {'aɪ', 'aʊ', 'eɪ', 'oʊ', 'ɔɪ', '#', '|', '||'}
diphthongs_add = set()
for i in split_diphtongs_IPA.values():
    diphthongs_add |= set(i)
english_ipa_comparison = (english_ipa | diphthongs_add) - delete

In [ ]:
# get the Yoruba inventory
yoruba_ipa_full = {'m', 'i', 'k', 'j', 'u', 'a', 'w', 'n', 't', 'l', 's', 'b', 'e',
              'o', 'ɡ', 'h', 'd', 'r', 'f', 'ɛ', 'ʃ', 'ɔ', 'd͡ʒ', '˦', '˨', 'ĩ',
              'ũ', 'ɡ͡b', 'k͡p', 'õ', 'ẽ', '˧', 'ŋ'}

In [ ]:
# tools to substitute Yoruba
yoruba_marginal = {'õ', 'ẽ', 'ŋ'}
yoruba_tones = {'˧', '˦', '˨'}

In [ ]:
yoruba_ipa = yoruba_ipa_full - yoruba_tones - yoruba_marginal

In [ ]:
# COMPUTE DISTANCES
! pip install panphon

In [ ]:
import panphon
import panphon.distance
ft = panphon.FeatureTable()

In [ ]:
exr = ['+syl', '+son', '-cons', '+cont', '0', '-lat', '-nas', '+strid', '+voi',
       '-sg', '-cg', '+ant', '+cor', '+distr', '-lab', '-hi', '-lo', '-back',
       '0round', '-velaric', '-tense', '-long', '0hitone', '0hireg']
er = ['+syl', '+son', '-cons', '+cont', '0', '-lat', '-nas', '+strid', '+voi',
       '-sg', '-cg', '+ant', '+cor', '+distr', '-lab', '-hi', '-lo', '-back',
       '0round', '-velaric', '-tense', '-long', '0hitone', '0hireg']

In [ ]:
def compute_distance(ipa1, ipa2):
    s1 = ft.word_fts(ipa1)
    s2 = ft.word_fts(ipa2)
    assert len(s1) == 1 and len(s2) == 1, f"the string {ipa1} or {ipa2} is not a phone"
    s1 = np.array(s1[0].numeric())
    s2 = np.array(s2[0].numeric())
    cor = (s1 - s2) / 2
    dist = sum(abs(s1 - s2)) / len(s1)
    return round(dist, 2)

In [ ]:
print(f"'o' and 'ʊ': {compute_distance('o', 'ʊ')}\t'o' and 'ĩ': {compute_distance('o', 'ĩ')}\t'o' and 'ɡ': {compute_distance('o', 'ɡ')}")

'o' and 'ʊ': 0.17	'o' and 'ĩ': 0.33	'o' and 'ɡ': 0.58


In [ ]:
matrix = pd.DataFrame(0, index=list(yoruba_ipa), columns=list(english_ipa_comparison))

In [ ]:
for y_ipa in yoruba_ipa:
    for e_ipa in english_ipa_comparison:
        matrix.loc[y_ipa, e_ipa] = compute_distance(y_ipa, e_ipa)

/tmp/ipython-input-16-3682877408.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.17' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[y_ipa, e_ipa] = compute_distance(y_ipa, e_ipa)
/tmp/ipython-input-16-3682877408.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.29' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[y_ipa, e_ipa] = compute_distance(y_ipa, e_ipa)
/tmp/ipython-input-16-3682877408.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.29' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matrix.loc[y_ipa, e_ipa] = compute_distance(y_ipa, e_ipa)
/tmp/ipython-input-16-3682877408.py:3

In [ ]:
# Display closest correspondences to each Yoruba phoneme
for sound in yoruba_ipa:
    print(sound, list(matrix.loc[sound].sort_values(ascending=True).index)[:3])

print('\n------\n')
for sound in english_ipa_comparison:
    print(sound, list(matrix.loc[:, sound].sort_values(ascending=True).index)[:3])

i ['i', 'ɪ', 'ɨ']
ɔ ['ɔ', 'o', 'ə']
o ['o', 'ʌ', 'ɔ']
w ['w', 'ʍ', 'u']
ĩ ['i', 'ɪ', 'ɨ']
ɡ ['ɡ', 'k', 'ŋ']
d ['d', 't', 'ð']
d͡ʒ ['d͡ʒ', 't͡ʃ', 'ʒ']
t ['t', 'd', 'θ']
k͡p ['k', 'ɡ', 'p']
h ['h', 'k', 'ʔ']
r ['ɾ', 'l', 'ð']
l ['l', 'ɾ', 'ð']
ũ ['u', 'ʉ', 'o']
b ['b', 'p', 'v']
n ['n', 'd', 'm']
ʃ ['ʃ', 'ʒ', 't͡ʃ']
j ['j', 'i', 'ɪ']
u ['u', 'ʉ', 'o']
k ['k', 'ɡ', 'h']
a ['a', 'ɑ', 'æ']
e ['e', 'æ', 'i']
f ['f', 'v', 'p']
m ['m', 'b', 'n']
ɡ͡b ['ɡ', 'b', 'k']
ɛ ['ɛ', 'ɪ', 'e']
s ['s', 'z', 't']

------

æ ['a', 'e', 'i']
ɑ ['a', 'o', 'e']
ɜ˞ ['ɔ', 'o', 'w']
o ['o', 'ɔ', 'a']
ɡ ['ɡ', 'k', 'ɡ͡b']
ð ['d', 't', 'l']
d ['d', 't', 'n']
t͡ʃ ['d͡ʒ', 'ʃ', 's']
d͡ʒ ['d͡ʒ', 'ʃ', 'd']
t ['t', 'd', 's']
ɾ ['r', 'l', 'd']
b ['b', 'm', 'ɡ͡b']
ʉ ['u', 'ũ', 'o']
p ['b', 'f', 'k͡p']
u ['u', 'ũ', 'o']
k ['k', 'ɡ', 'k͡p']
a ['a', 'o', 'e']
ɪ ['i', 'ɛ', 'j']
m ['m', 'b', 'n']
ʍ ['w', 'u', 'ũ']
ɹ ['r', 'j', 'l']
ɛ ['ɛ', 'e', 'i']
ɨ ['i', 'o', 'ĩ']
s ['s', 't', 'ʃ']
i ['i', 'ĩ', 'e']
w ['w', 'u', 'j']
z

In [ ]:
matrix.sort_index(axis=1, inplace=True)

In [ ]:
matrix.sort_index(axis=0, inplace=True)

In [ ]:
matrix

a     b     d   d͡ʒ     e     f     h     i     j     k  ...     ɹ  \
a    0.00  0.67  0.71  0.88  0.17  0.75  0.42  0.25  0.42  0.67  ...  0.62   
b    0.67  0.00  0.21  0.46  0.50  0.25  0.50  0.58  0.50  0.42  ...  0.62   
d    0.71  0.21  0.00  0.33  0.54  0.46  0.54  0.62  0.54  0.46  ...  0.42   
d͡ʒ  0.88  0.46  0.33  0.00  0.71  0.54  0.62  0.79  0.62  0.54  ...  0.75   
e    0.17  0.50  0.54  0.71  0.00  0.58  0.42  0.08  0.25  0.67  ...  0.46   
f    0.75  0.25  0.46  0.54  0.58  0.00  0.42  0.67  0.58  0.50  ...  0.71   
h    0.42  0.50  0.54  0.62  0.42  0.42  0.00  0.50  0.33  0.25  ...  0.62   
i    0.25  0.58  0.62  0.79  0.08  0.67  0.50  0.00  0.17  0.58  ...  0.38   
ĩ   0.33  0.67  0.71  0.88  0.17  0.75  0.58  0.08  0.25  0.67  ...  0.46   
j    0.42  0.50  0.54  0.62  0.25  0.58  0.33  0.17  0.00  0.42  ...  0.29   
k    0.67  0.42  0.46  0.54  0.67  0.50  0.25  0.58  0.42  0.00  ...  0.71   
k͡p  0.71  0.29  0.50  0.67  0.71  0.38  0.38  0.62  0.54  0.12  ...  0.75   
l    0.62  0.46  0.25  0.58  0.46  0.54  0.46  0.54  0.46  0.71  ...  0.33   
m    0.67  0.17  0.38  0.62  0.50  0.42  0.50  0.58  0.50  0.58  ...  0.62   
n    0.71  0.38  0.17  0.50  0.54  0.62  0.54  0.62  0.54  0.62  ...  0.42   
o    0.17  0.67  0.71  0.88  0.17  0.75  0.42  0.25  0.42  0.67  ...  0.46   
r    0.58  0.50  0.29  0.54  0.50  0.58  0.50  0.50  0.42  0.67  ...  0.29   
s    0.79  0.46  0.25  0.42  0.62  0.21  0.46  0.71  0.62  0.54  ...  0.50   
t    0.79  0.29  0.08  0.42  0.62  0.38  0.46  0.71  0.62  0.38  ...  0.50   
u    0.33  0.67  0.88  1.04  0.33  0.75  0.58  0.25  0.42  0.67  ...  0.46   
ũ   0.42  0.75  0.96  1.12  0.42  0.83  0.67  0.33  0.50  0.75  ...  0.54   
w    0.50  0.58  0.79  0.88  0.50  0.67  0.42  0.42  0.25  0.50  ...  0.38   
ɔ    0.25  0.67  0.71  0.88  0.25  0.75  0.42  0.33  0.42  0.67  ...  0.46   
ɛ    0.25  0.50  0.54  0.71  0.08  0.58  0.42  0.17  0.25  0.67  ...  0.46   
ɡ    0.58  0.33  0.38  0.46  0.58  0.58  0.33  0.50  0.33  0.08  ...  0.62   
ɡ͡b  0.62  0.21  0.42  0.58  0.62  0.46  0.46  0.54  0.46  0.21  ...  0.67   
ʃ    0.79  0.54  0.42  0.25  0.62  0.29  0.38  0.71  0.54  0.46  ...  0.67   

        ɾ     ʃ     ʉ     ʊ     ʌ     ʍ     ʒ     ʔ     θ  
a    0.58  0.79  0.38  0.33  0.08  0.58  0.71  0.50  0.71  
b    0.50  0.54  0.71  0.75  0.58  0.67  0.46  0.58  0.38  
d    0.29  0.42  0.92  0.79  0.62  0.88  0.33  0.62  0.25  
d͡ʒ  0.54  0.25  1.00  0.96  0.79  0.96  0.17  0.71  0.42  
e    0.50  0.62  0.38  0.33  0.08  0.58  0.54  0.50  0.54  
f    0.58  0.29  0.79  0.83  0.67  0.58  0.38  0.67  0.29  
h    0.50  0.38  0.62  0.50  0.33  0.33  0.46  0.25  0.38  
i    0.50  0.71  0.29  0.25  0.17  0.50  0.62  0.58  0.62  
ĩ   0.58  0.79  0.38  0.33  0.25  0.58  0.71  0.67  0.71  
j    0.42  0.54  0.46  0.33  0.33  0.33  0.46  0.42  0.54  
k    0.67  0.46  0.71  0.58  0.58  0.42  0.54  0.33  0.46  
k͡p  0.71  0.58  0.58  0.62  0.62  0.38  0.67  0.46  0.50  
l    0.21  0.50  0.83  0.71  0.54  0.79  0.42  0.71  0.33  
m    0.50  0.71  0.71  0.75  0.58  0.67  0.62  0.58  0.54  
n    0.29  0.58  0.92  0.79  0.62  0.88  0.50  0.62  0.42  
o    0.67  0.79  0.21  0.17  0.08  0.42  0.71  0.50  0.71  
r    0.00  0.54  0.71  0.67  0.58  0.75  0.46  0.75  0.38  
s    0.38  0.17  1.00  0.88  0.71  0.79  0.25  0.71  0.17  
t    0.38  0.33  1.00  0.88  0.71  0.79  0.42  0.54  0.17  
u    0.75  0.96  0.04  0.17  0.25  0.25  0.88  0.67  0.88  
ũ   0.83  1.04  0.12  0.25  0.33  0.33  0.96  0.75  0.96  
w    0.67  0.79  0.21  0.25  0.42  0.08  0.71  0.50  0.79  
ɔ    0.67  0.79  0.29  0.08  0.17  0.42  0.71  0.50  0.71  
ɛ    0.50  0.62  0.46  0.25  0.17  0.58  0.54  0.50  0.54  
ɡ    0.58  0.54  0.62  0.50  0.50  0.50  0.46  0.42  0.54  
ɡ͡b  0.62  0.67  0.50  0.54  0.54  0.46  0.58  0.54  0.58  
ʃ    0.54  0.00  1.00  0.88  0.71  0.71  0.08  0.62  0.17  

[27 rows x 44 columns]

In [ ]:
# descipher Yoruba label from English
def english_to_yoruba_label(ipa: str) -> str:
    return matrix.loc[sound].sort_values(ascending=False).index[0]

In [ ]:
print(f'English TIMIT inventory size: {len(timit_to_ipa)}')
print(f'English inventory size: {len(english_ipa_comparison)}')
print(f'Yoruba PHOIBLE inventory size: {len(yoruba_ipa_full)}')
print(f'Yoruba inventory size: {len(yoruba_ipa)}')

English TIMIT inventory size: 63
English inventory size: 44
Yoruba PHOIBLE inventory size: 33
Yoruba inventory size: 27


In [ ]:
dst = panphon.distance.Distance()

In [ ]:
print(f"Yo. /ed͡ʒi/ vs. Eng. /ɛd͡ʒi/ : {round(dst.feature_edit_distance('ed͡ʒi', 'ɛd͡ʒi'), 2)}")

Yo. /ed͡ʒi/ vs. Eng. /ɛd͡ʒi/ : 0.04


In [ ]:
print(f"Yo. /ki nĩ a mũ wa aje/ vs. pseudo Eng. /kilæ mua jɪ/ : {round(dst.feature_edit_distance('kilæ mua jɪ', 'ki nĩ a mũ wa aje'), 2)}")

Yo. /ki nĩ a mũ wa aje/ vs. pseudo Eng. /kilæ mua jɪ/ : 3.04


In [ ]:
### extract the alignment matrix instead of distance in the panphon method
def new_ed_distance(self, del_cost, ins_cost, sub_cost, start, source, target):
    """Return minimum edit distance, parameterized, slow

    Args:
        del_cost (function): cost function for deletion
        ins_cost (function): cost function for insertion
        sub_cost (function): cost function for substitution
        start (sequence): start symbol: string for strings, list for lists,
                            list of list for list of lists
        source (sequence): source string/sequence of feature vectors
        target (sequence): target string/sequence of feature vectors

    Returns:
        Number: minimum edit distance from source to target, with edit costs
                as defined
    """
    # Get lengths of source and target
    n, m = len(source), len(target)
    source, target = start + source, start + target
    # Create "matrix"
    d = []
    for i in range(n + 1):
        d.append((m + 1) * [None])
    # Initialize "matrix"
    d[0][0] = 0
    for i in range(1, n + 1):
        d[i][0] = d[i - 1][0] + del_cost(source[i])
    for j in range(1, m + 1):
        d[0][j] = d[0][j - 1] + ins_cost(target[j])
    # Recurrence relation
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            d[i][j] = min([
                d[i - 1][j] + del_cost(source[i]),
                d[i - 1][j - 1] + sub_cost(source[i], target[j]),
                d[i][j - 1] + ins_cost(target[j]),
            ])
    return d, source, target

In [ ]:
panphon.distance.Distance.min_edit_distance = new_ed_distance

In [ ]:
dst = panphon.distance.Distance()

In [ ]:
lev = dst.feature_edit_distance('kilæ mua jɪ', 'ki nĩ a mũ wa aje')

In [ ]:
lev = np.array(lev)

In [ ]:
lev = lev.round(2)

In [ ]:
for i in lev:
    print(i)

[ 0.    0.92  1.83  2.77  3.69  4.6   5.52  6.44  7.35  8.27  9.19 10.1
 11.02]
[ 0.92  0.    0.92  1.85  2.77  3.69  4.6   5.52  6.44  7.35  8.27  9.19
 10.1 ]
[1.83 0.92 0.   0.94 1.85 2.77 3.69 4.6  5.52 6.44 7.35 8.27 9.19]
[2.77 1.85 0.94 0.12 1.04 1.96 2.87 3.79 4.71 5.62 6.54 7.46 8.38]
[3.69 2.77 1.85 1.04 0.25 1.08 2.   2.92 3.83 4.75 5.67 6.58 7.5 ]
[4.6  3.69 2.77 1.96 1.17 0.58 1.08 2.   2.92 3.83 4.75 5.67 6.58]
[5.52 4.6  3.69 2.87 2.08 1.33 0.92 1.12 2.04 2.96 3.87 4.79 5.71]
[6.44 5.52 4.6  3.79 3.   2.08 1.67 1.12 1.38 2.04 2.96 3.87 4.79]
[7.35 6.44 5.52 4.71 3.92 3.   2.33 1.92 1.25 1.58 2.25 2.96 3.87]
[8.27 7.35 6.44 5.62 4.79 3.92 3.25 2.54 2.12 1.42 1.75 2.33 3.04]


In [ ]:
w1 = 'kilæ mua jɪ'
w2 = 'ki nĩ a mũ wa aje'
i, j = lev.shape
cell = [[]]*max(i,j)
i, j = i-1, j-1
while i > 0 or j > 0:
    o1 = lev[i-1, j-1]
    o2 = lev[i-1, j]
    o3 = lev[i, j-1]
    if min(o1, o2, o3) == o1:
        i, j = i-1, j-1
    elif min(o1, o2, o3) == o2:
        i, j = i-1, j
    else:
        i, j = i, j-1
    print(i, j)

9 11
9 10
9 9
8 8
7 7
6 6
5 5
4 4
3 3
2 2
1 1
0 0


In [ ]:
lev.shape

(10, 13)